### ISSUE TITLE
As a registered user, I want to log in to the webpage with my username and password.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#1]
### Acceptance Criteria
- [x]  Upon successful login, the home layout is shown and the user is logged in and able to view authenticated pages.
- [x]  If the login fails, an error is shown and the user cannot view the home layout.

### Development Tasks
- [x] sopra-fs23-group-32/SoPra23_Client#1
- [x] sopra-fs23-group-32/SoPra23_Server#24
- [x] sopra-fs23-group-32/SoPra23_Server#25
- [x] sopra-fs23-group-32/SoPra23_Client#2
