### ISSUE TITLE
As a logged-in user, I want to view an overall ranking of the users.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#10]
### Acceptance Criteria
- [x]  After clicking on the ‘Rank’ button at the home page, you can view the overall ranking of all registered users.
- [x]  By clicking on a username in the ranking list, you are redirected to a profile page of the selected user. 
- [x]  The profile page contains the following data belonging to the selected user: username, online status, creation date, overall score, and how many games they have played. 
- [x]  The ranking and the profile page are only accessible for logged-in users.

### Development Tasks

- [x] sopra-fs23-group-32/SoPra23_Server#68
- [x] sopra-fs23-group-32/SoPra23_Client#22
- [x] sopra-fs23-group-32/SoPra23_Client#23
