### ISSUE TITLE
As a logged-in user, I want to have an overview of the user's points earned in each city category and their rankings.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#11]
### Acceptance Criteria
- [x]  After clicking on the ‘Rank’ button at the home page, you are redirected to the ‘Overall Ranking’ page.
- [x]  By clicking on the ‘European Cities’ tab, you can view the ranking of all registered users answering questions regarding European cities and their points earned.
- [x]  By clicking on a username in the ranking list, you are redirected to a profile page of the selected user.
- [x] The profile page contains the following data belonging to the selected user: username, online status, creation date, overall score, and how many times they have played. 
- [x] The ranking and the profile page are only accessible for logged-in users.

### Development Tasks

- [x] sopra-fs23-group-32/SoPra23_Server#69
- [x] sopra-fs23-group-32/SoPra23_Client#24
- [x] sopra-fs23-group-32/SoPra23_Client#25
- [x] sopra-fs23-group-32/SoPra23_Server#78
- [x] sopra-fs23-group-32/SoPra23_Client#26
