### ISSUE TITLE
As a logged-in user, I want to view my detailed game history and a summarization of them.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#12]
### Acceptance Criteria
- [x]  After clicking on the ‘History’ button at the home page, you can inspect the previous game history.
- [x] For each game history record, you can view when you play this game, how many cities you have guessed correctly and how many you have guessed wrongly.
- [x] The game history is only accessible for logged-in users.

### Development Tasks
- [x] sopra-fs23-group-32/SoPra23_Server#16
- [x] sopra-fs23-group-32/SoPra23_Server#17
- [x] sopra-fs23-group-32/SoPra23_Server#18
- [x] sopra-fs23-group-32/SoPra23_Server#19
- [x] sopra-fs23-group-32/SoPra23_Client#27
- [x] sopra-fs23-group-32/SoPra23_Client#28
- [x] #122
