### ISSUE TITLE
As a logged-in user, I want to view my profile in order to see my profile information.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#3]
### Acceptance Criteria
- [x]  Given a logged-in user clicks on his profile, he is then redirected to his profile page. Then on the profile page a logged in user can view the data belonging the user such as his username. This data includes: username, online status, creation date, overall score, games played

### Development Tasks

- [x] sopra-fs23-group-32/SoPra23_Client#5
- [x] sopra-fs23-group-32/SoPra23_Server#28
- [x] sopra-fs23-group-32/SoPra23_Client#6
