### ISSUE TITLE
As a logged-in user, I want to edit my profile to change my credentials such as username or password.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#4]
### Acceptance Criteria
- [x]  From the profile page, the user can access an "edit" page, where he can change his personal information
- [ ]  Given a new and updated password or username that has not been selected yet, when the user presses on save, then the credentials are updated in the database and the profile is updated.
- [x]  In case of failure such as the new username being taken or empty, then an error will be displayed.

### Development Tasks

- [x] sopra-fs23-group-32/SoPra23_Client#7
- [ ] sopra-fs23-group-32/SoPra23_Client#8
- [x] sopra-fs23-group-32/SoPra23_Server#32
- [x] sopra-fs23-group-32/SoPra23_Server#33
