### ISSUE TITLE
As a logged-in user, I want to be able to view the home layout to have access to different functions and information.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#5]
### Acceptance Criteria
- [x]  Given a user is on the home layout, when he wants to view his profile then the user can select the view profile component on the home layout to be directed to the profile.
- [x]  Given a user is on the home layout, when he wants to start a game, then the user can select the "start game" component on the home layout.
- [x]  Given a user is on the home screen, when he wants to logout then he can click on the log out component on the home screen.

### Development Tasks

- [x] sopra-fs23-group-32/SoPra23_Client#9
- [x] sopra-fs23-group-32/SoPra23_Client#10
- [x] sopra-fs23-group-32/SoPra23_Client#11
- [x] sopra-fs23-group-32/SoPra23_Client#13
- [x] sopra-fs23-group-32/SoPra23_Client#14
- [x] sopra-fs23-group-32/SoPra23_Server#44
