### ISSUE TITLE
As a logged-in user, I want to be able to choose the Multiplayers Mode and invite my friends through a link

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#8]
### Acceptance Criteria
- [x]  By choosing "multiplayer" in the game lobby, the "invite to game" button activates
- [x]  Upon pressing the "invite to game" button, the user gets redirected to the "Invite Game" page
- [x]  In the "invite game" page, the user sees a link, which he can copy
- [x]  To directly copy it, he can press on the "Copy" logo to save it to the clipboard

### Development Tasks

- [x] sopra-fs23-group-32/SoPra23_Client#18 
- [x] sopra-fs23-group-32/SoPra23_Client#19 
- [x] sopra-fs23-group-32/SoPra23_Server#90
- [x] sopra-fs23-group-32/SoPra23_Server#91
- [x] sopra-fs23-group-32/SoPra23_Client#20
