### ISSUE TITLE
In a multiplayer game, we want to know who is the final winner among the players.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs23-group-32/SoPra23_Server#9]
### Acceptance Criteria
- [x]  In multiplayer games, in addition to your own score, you can also see the current scores of other players on the game page, with all players' scores listed in ascending order.
- [x]  At the end of the game, the ranking of the total points scored by everyone in the game will appear on the page, as well as the winner.

### Development Tasks

- [x] sopra-fs23-group-32/SoPra23_Client#21
- [x] sopra-fs23-group-32/SoPra23_Server#71
- [x] sopra-fs23-group-32/SoPra23_Server#75
