### ISSUE TITLE
As a logged-in user playing singleplayer mode, I want to be able to click on my guess and verify this using the submit button and see if my answer is correct

### ISSUE THREAD

**Issue by dominic1712** [sopra-fs23-group-32/SoPra23_Server#98]
### Acceptance Criteria
- [x]  Playing a singleplayer game and entering a new round, the following items should appear on the screen: the picture, 4 options to choose from one of them being the solution, the round number, the players score and a timer counting down from 30 seconds
- [x]  After pressing on an option and hitting the submit button, the round is finished and the solution will shown to the players
- [x]  If the timer hits 0 and the submit button hasn't been pressed yet, the round ends and the last guess of the user counts as his final guess and the user is redirected to the "solution" screen
- [x]  The screen shows the user's answer and the solution. If both are the same, it's green. If they are different, the user's answer gets marked orange and the correct one gets marked as green
- [x] If he has reviewed the answer, he can click "next", which will bring him to the new countdown screen

### Development Tasks
- [x] sopra-fs23-group-32/SoPra23_Server#99 
- [x] sopra-fs23-group-32/SoPra23_Server#100
- [x] sopra-fs23-group-32/SoPra23_Client#30 
- [x] sopra-fs23-group-32/SoPra23_Server#54
- [x] sopra-fs23-group-32/SoPra23_Client#29 
- [x] sopra-fs23-group-32/SoPra23_Server#55
- [x] sopra-fs23-group-32/SoPra23_Server#112
- [x] sopra-fs23-group-32/SoPra23_Client#43
- [x] sopra-fs23-group-32/SoPra23_Client#55
- [x] sopra-fs23-group-32/SoPra23_Server#115
